Repository kami-blue/client, pull requests merged in 2020-03, with the labels that each got.

#509 probably fixes the crash
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.java
Labels: bug/module

#510 [Added] MidClickFriends Closes #302
  src/main/java/me/zeroeightsix/kami/command/commands/FriendCommand.java
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/MidClickFriends.java
Labels: new/module

#485 XCarry
  src/main/java/me/zeroeightsix/kami/module/modules/misc/XCarry
Labels: 3 - Review, new/module, review-pending

#468 Update CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.java
Labels: 3 - Review, enhancement/module, review-pending

#519 Bumped bunch of things
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement/other

#516 Finish offhandgap
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTotem.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/OffhandGap.java
Labels: bug/module, enhancement/module, review-pending

#522 Feature/offhandgap#379
  src/main/java/me/zeroeightsix/kami/module/modules/combat/OffhandGap.java
Labels: enhancement/module

#525 feature/pvpinfo#520
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Fastuse.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
Labels: enhancement/module

#526 Make autofish faster
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoFish.java
Labels: enhancement/module

#538 fix not searching if items were in offhand <3
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
Labels: bug/gui, bug/other

#546 Add hunger options to autoeat and don't eat bad food
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.java
Labels: enhancement/module

#549 Update combat improvements
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.java
Labels: -meta

#550 Add a ton of options to AntiSpam and make detection better
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java
Labels: enhancement/module

#551 Update combat improvements
  gradle.properties
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/XRayCommand.java
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InventoryViewer.java
  src/main/resources/mcmod.info
Labels: -meta

#561 Update combat improvements
  scripts/hook.sh
  scripts/preHook.sh
Labels: -meta

#566 Make antispam way more efficient and rewrite it
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java
Labels: enhancement/module

#569 Update combat improvements
  src/main/java/me/zeroeightsix/kami/command/Command.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootScrollpaneUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoQMain.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoReply.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/CustomChat.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FormatChat.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Auto32k.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoExp.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoFeetPlace.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTotem.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoFish.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoSpawner.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/ConsoleSpam.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordSettings.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/FakeGamemode.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.java
  src/main/java/me/zeroeightsix/kami/util/ColourSet.java
  src/main/java/me/zeroeightsix/kami/util/InfoCalculator.java
Labels: -meta

#593 Autoeat no longer eats poisonous potatoes
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.java
Labels: enhancement/module

#595 Switch colors to use TextFormatting
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatTimestamp.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/setting/converter/EnumConverter.java
  src/main/java/me/zeroeightsix/kami/util/ColourUtils.java
  src/main/java/me/zeroeightsix/kami/util/TimeUtil.java
Labels: enhancement/other

#599 Update combat improvements
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatTimestamp.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/ActiveModules.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/util/ColourTextFormatting.java
Labels: -meta

#590 added aliases to commands
  src/main/java/me/zeroeightsix/kami/command/Command.java
  src/main/java/me/zeroeightsix/kami/command/CommandManager.java
  src/main/java/me/zeroeightsix/kami/command/commands/ToggleCommand.java
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiChat.java
Labels: enhancement/other

#610 Add GUI for BeaconSelector
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/TestForItems.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/BeaconSelector.java
  src/main/java/me/zeroeightsix/kami/util/BeaconGui.java
Labels: enhancement/module

#612 Update combat improvements
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoQMain.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InventoryViewer.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/BeaconSelector.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordSettings.java
  src/main/java/me/zeroeightsix/kami/util/BeaconGui.java
  src/main/java/me/zeroeightsix/kami/util/GuiFrameUtil.java
  src/main/java/me/zeroeightsix/kami/util/InfoCalculator.java
Labels: -meta

#521 General Combat Improvements
  src/main/java/me/zeroeightsix/kami/event/events/EntityUseTotemEvent.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiChainPop.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoOffhand.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/OffhandGap.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/TotemPopCounter.java
  src/main/java/me/zeroeightsix/kami/module/modules/experimental/HoleFiller.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.java
Labels: bug/module, enhancement/module, new/module

#635 Breaking Warning
  src/main/java/me/zeroeightsix/kami/module/modules/combat/BreakingWarning.java
Labels: new/module

#609 Rewrite of VectorUtil (with sleep version)
  src/main/java/me/zeroeightsix/kami/util/VectorUtil.java
Labels: new/other
