Repository kami-blue/client, pull requests merged in 2020-01, with the labels that each got.

#361 fix bug Chunkfinder bug
  src/main/java/me/zeroeightsix/kami/module/modules/zeroeightysix/render/ChunkFinder.java
Labels: bug

#338 True Durability and Friends List
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiPlayerTabOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/zeroeightysix/render/ExtraTab.java
  src/main/java/me/zeroeightsix/kami/module/modules/zeroeightysix/render/TabFriends.java
Labels: enhancement, new-feature/gui

#364 Visualrange
  src/main/java/me/zeroeightsix/kami/module/modules/misc/VisualRange.java
Labels: new-feature/gui

#365 nobreakanimation
  src/main/java/me/zeroeightsix/kami/module/modules/player/NoBreakAnimation.java
Labels: new-feature

#367 Feature/pull32k
  src/main/java/me/zeroeightsix/kami/module/modules/bewwawho/combat/Pull32k.java
Labels: new-feature

#369 Feature/rpcusers
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/util/bewwawho/RichPresence.java
Labels: new-feature

#376 Feature/aliases to close #358
  src/main/java/me/zeroeightsix/kami/command/Command.java
  src/main/java/me/zeroeightsix/kami/command/CommandManager.java
  src/main/java/me/zeroeightsix/kami/command/commands/CommandsCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/ConfigCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/CreditsCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/EntityStatsCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/FriendCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/HelpCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/PathCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/SignBookCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/TeleportCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/ToggleCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/VanishCommand.java
Labels: good-first-issue, new-feature, new-feature/gui
