Repository kami-blue/client, pull requests merged in 2020-08, with the labels that each got.

#1103 Made final jar file smaller
  build.gradle
  src/main/java/me/zeroeightsix/installer/Installer.java
  src/main/resources/installer/00.jpg
  src/main/resources/installer/01.jpg
  src/main/resources/installer/02.jpg
  src/main/resources/installer/03.jpg
  src/main/resources/installer/beta.png
  src/main/resources/installer/rawimagefiles/00.png
  src/main/resources/installer/rawimagefiles/01.png
  src/main/resources/installer/rawimagefiles/02.png
  src/main/resources/installer/rawimagefiles/03.png
  src/main/resources/installer/stable.png
  src/main/resources/kami.png
Labels: 03-testing-pending, enhancement/other

#1117 Added Strafe
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Strafe.kt
  src/main/java/me/zeroeightsix/kami/util/MovementUtils.kt
Labels: 03-testing-pending, new/module

#1134 Render bug fixes
  src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/HoleESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt
  src/main/java/me/zeroeightsix/kami/util/BetterArrayList.kt
  src/main/java/me/zeroeightsix/kami/util/ESPRenderer.kt
  src/main/java/me/zeroeightsix/kami/util/KamiTessellator.kt
Labels: 03-testing-pending, bug/module, enhancement/module

#1138 Fixed PlayerModel enchant glint issue #995
  src/main/java/me/zeroeightsix/kami/module/modules/client/InventoryViewer.java
Labels: 03-testing-pending, bug/gui

#1139 Added NCPStrict to ElytraFlight
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
Labels: 02-review-pending, enhancement/module

#1124 Updated AntiAFK to work on 2b2t
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.java
Labels: 02-review-pending, enhancement/module

#1162 Fixed KamiMoji incompatibility with SmoothFont
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinFontRenderer.java
Labels: 02-review-pending, enhancement/gui

#1163 Configurable Color for Tracer and StorageESP
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiEnumButtonUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiFrameUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootCheckButtonUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootColorizedCheckButtonUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootScrollpaneUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootSliderUI.java
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiChat.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatTimestamp.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/ActiveModules.java
  src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/client/InventoryViewer.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/TotemPopCounter.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ArmourHUD.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/BreakingESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/EyeFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/HoleESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/StorageESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Trajectories.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt
  src/main/java/me/zeroeightsix/kami/util/ColourConverter.java
  src/main/java/me/zeroeightsix/kami/util/ColourHolder.java
  src/main/java/me/zeroeightsix/kami/util/ESPRenderer.kt
  src/main/java/me/zeroeightsix/kami/util/HueCycler.java
  src/main/java/me/zeroeightsix/kami/util/KamiTessellator.kt
  src/main/java/me/zeroeightsix/kami/util/colourUtils/ColourConverter.kt
  src/main/java/me/zeroeightsix/kami/util/colourUtils/ColourHolder.kt
  src/main/java/me/zeroeightsix/kami/util/colourUtils/ColourTextFormatting.java
  src/main/java/me/zeroeightsix/kami/util/colourUtils/ColourUtils.java
  src/main/java/me/zeroeightsix/kami/util/colourUtils/DyeColors.kt
  src/main/java/me/zeroeightsix/kami/util/colourUtils/HueCycler.kt
Labels: 02-review-pending, enhancement/module, enhancement/other

#1181 Fixed BreakingESP showing after block was broken
  src/main/java/me/zeroeightsix/kami/module/modules/render/BreakingESP.kt
Labels: 03-testing-pending, bug/module

#1164 Fixed render modules jitters in paused single player world
  src/main/java/me/zeroeightsix/kami/module/modules/render/Breadcrumbs.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/EyeFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt
  src/main/java/me/zeroeightsix/kami/util/ESPRenderer.kt
  src/main/java/me/zeroeightsix/kami/util/KamiTessellator.kt
Labels: 03-testing-pending, bug/other

#1170 Removed Forgelin
  build.gradle
  src/main/java/me/zeroeightsix/kami/mixin/MixinLoaderForge.java
  src/main/java/net/shadowfacts/forgelin/preloader/ForgelinSetup.java
Labels: 03-testing-pending, enhancement/other

#1179 Added animations to ElytraFlight
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinModelPlayer.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/resources/mixins.kami.json
Labels: 02-review-pending, bug/other, enhancement/module

#1173 Added MidClickPearl
  src/main/java/me/zeroeightsix/kami/module/modules/combat/MidClickPearl.kt
Labels: new/module

#1187 Revamped ElytraReplace
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraReplace.kt
Labels: enhancement/module

#1191 Added ChestStealer and some bug fix
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiStealButton.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiContainer.java
  src/main/java/me/zeroeightsix/kami/module/modules/player/ChestStealer.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt
  src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt
  src/main/resources/mixins.kami.json
Labels: new/module

#1184 Fixed white screen caused by Radar
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.java
Labels: 03-testing-pending, bug/gui

#1202 Improved Search Rendering and Calculation
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/BreakingESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/EyeFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/HoleESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/SelectionHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/StorageESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Trajectories.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt
  src/main/java/me/zeroeightsix/kami/util/ESPRenderer.kt
  src/main/java/me/zeroeightsix/kami/util/KamiTessellator.kt
Labels: 02-review-pending, bug/module, enhancement/module

#1208 Added HighPingOptimize to ElytraFlight and fixed animation bugs
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinModelBiped.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderPlayer.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Flight.kt
  src/main/resources/mixins.kami.json
Labels: 02-review-pending, bug/module, enhancement/module

#1201 Added Items to Nametags
  src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.java
Labels: 02-review-pending, bug/module, enhancement/module

#1211 Radar render fix and smoother PlayerModel
  src/main/java/me/zeroeightsix/kami/gui/font/CFontRenderer.java
  src/main/java/me/zeroeightsix/kami/gui/kami/RootFontRenderer.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiEnumButtonUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootButtonUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootCheckButtonUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootLabelUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/RootSliderUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/TabGuiUI.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiInventory.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/PlayerModel.kt
Labels: 02-review-pending, bug/gui, enhancement/module

#1206 Fixed Anti-Duplicate bug + Cleanup
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.kt
Labels: 02-review-pending, bug/module, enhancement/module

#1196 Added Potion Effects UI
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/component/Potions.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiPotionUi.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiTheme.java
  src/main/java/me/zeroeightsix/kami/util/PotionInfo.kt
  src/main/java/me/zeroeightsix/kami/util/textUtils/RomanNumerals.kt
Labels: 01-changes-requested, enhancement/gui

#1227 Optimized config saving and added autosaving
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/ConfigCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/ConfigCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/MacroCommand.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinMinecraft.java
  src/main/java/me/zeroeightsix/kami/module/MacroManager.kt
  src/main/java/me/zeroeightsix/kami/module/WaypointManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/CommandConfig.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ChunkFinder.java
  src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
  src/main/java/me/zeroeightsix/kami/util/Macro.kt
  src/main/java/me/zeroeightsix/kami/util/Timer.kt
  src/main/java/me/zeroeightsix/kami/util/Waypoint.kt
Labels: 02-review-pending, enhancement/other

#1236 Updated AutoFish to work on all servers, and made AutoRecast better
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoFish.kt
  src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
Labels: 02-review-pending, enhancement/module

#1237 Added brightness option to FullBright and rewrote
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityRenderer.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Brightness.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/FullBright.kt
Labels: 02-review-pending, enhancement/other

#1239 Fixed Spammer random mode does work with 1 line
  src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.kt
Labels: 03-testing-pending, bug/module

#1241 ChunkFinder bug fixes and small enhancement
  src/main/java/me/zeroeightsix/kami/module/modules/render/ChunkFinder.java
Labels: 02-review-pending, bug/module, enhancement/module

#1243 Fixed getting kicked while attempting to send empty message
  src/main/java/me/zeroeightsix/kami/util/MessageSendHelper.java
Labels: bug/other

#1253 Added 2D Render Utils
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.kt
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiFrameUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.kt
  src/main/java/me/zeroeightsix/kami/util/color/ColorHolder.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/GlStateUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/ProjectionUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/RenderUtils2D.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/VertexHelper.kt
  src/main/java/me/zeroeightsix/kami/util/math/Vec2d.kt
Labels: bug/other, enhancement/other, good-first-issue

#1183 Enhancements for Friends
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/ConfigCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/FriendCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/FriendCommand.kt
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/manager/mangers/FileInstanceManager.kt
  src/main/java/me/zeroeightsix/kami/manager/mangers/FriendManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/TotemPopCounter.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/MidClickFriends.kt
  src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
  src/main/java/me/zeroeightsix/kami/util/Friends.java
  src/main/java/me/zeroeightsix/kami/util/Friends.kt
  src/main/java/me/zeroeightsix/kami/util/Macro.kt
  src/main/java/me/zeroeightsix/kami/util/Waypoint.kt
Labels: 00-blocked, 01-changes-requested, bug/module, enhancement/other

#1250 Enhancement for FastUse
  src/main/java/me/zeroeightsix/kami/module/modules/player/Fastuse.kt
Labels: 03-testing-pending, enhancement/module

#1248 Fixed config loading not using config name in KAMIBlueLastConfig
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/ConfigCommand.kt
  src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
Labels: --testing-pending, -module, bug

#1256 Added PlayerPacketManager
  src/main/java/me/zeroeightsix/kami/event/events/OnUpdateWalkingPlayerEvent.kt
  src/main/java/me/zeroeightsix/kami/manager/mangers/PlayerPacketManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/java/me/zeroeightsix/kami/util/math/Vec2f.kt
Labels: -module, -other, enhancement, new

#1260 Added GUI Scaling Option
  src/main/java/me/zeroeightsix/kami/command/commands/FixGuiCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/FixGuiCommand.kt
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.kt
  src/main/java/me/zeroeightsix/kami/gui/UIRenderer.java
  src/main/java/me/zeroeightsix/kami/gui/UIRenderer.kt
  src/main/java/me/zeroeightsix/kami/gui/kami/DisplayGuiScreen.java
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiFrameUI.java
  src/main/java/me/zeroeightsix/kami/gui/rgui/component/container/use/Scrollpane.java
  src/main/java/me/zeroeightsix/kami/gui/rgui/component/use/InputField.java
  src/main/java/me/zeroeightsix/kami/module/modules/ClickGUI.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/InventoryViewer.java
  src/main/java/me/zeroeightsix/kami/module/modules/hidden/FixGui.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/LagNotifier.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/GlStateUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/GuiFrameUtil.kt
Labels: -gui, enhancement
