Repository kami-blue/client, pull requests merged in 2020-04, with the labels that each got.

#649 Add custom colors to active modules categories
  src/main/java/me/zeroeightsix/kami/command/Command.java
  src/main/java/me/zeroeightsix/kami/command/commands/ActiveModulesCommand.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/ActiveModules.java
Labels: enhancement/gui, enhancement/module

#678 Cleaner and faster packet cancel
  src/main/java/me/zeroeightsix/kami/module/modules/player/PacketCancel.java
Labels: enhancement/module

#667 Merge the update checker
  scripts/ver.sh
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiUpdateNotification.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiMainMenu.java
  src/main/java/me/zeroeightsix/kami/util/WebUtils.java
  src/main/resources/mixins.kami.json
Labels: enhancement/other, new/other

#679 update Aura
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.java
Labels: enhancement/module

#695 Make util.LogUtil append to file instead of overwriting it.
  src/main/java/me/zeroeightsix/kami/util/LogUtil.java
Labels: enhancement/other

#697 Improvements to LogUtil
  src/main/java/me/zeroeightsix/kami/util/LogUtil.java
Labels: enhancement/other

#698 Add a coordinate logger.
  src/main/java/me/zeroeightsix/kami/module/modules/hidden/CoordsLog.java
Labels: new/module

#706 Feature/eflight#616
  src/main/java/me/zeroeightsix/kami/event/events/PlayerTravelEvent.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayer.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.java
  src/main/resources/mixins.kami.json
Labels: enhancement/module

#731 Readded Search
  src/main/java/me/zeroeightsix/kami/command/commands/SearchCommand.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java
Labels: new/module

#733 Improvements to Search Module
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java
  src/main/java/me/zeroeightsix/kami/setting/builder/numerical/NumericalSettingBuilder.java
Labels: enhancement/module

#747 Add a Stashfinder module
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
Labels: new/module

#749 Scaffold tower
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.java
Labels: enhancement/module
