Repository kami-blue/client, pull requests merged in 2020-05, with the labels that each got.

#770 Fixed the color of AutoTotem text in active modules.
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
Labels: bug/gui

#776 License part 2 and 3?????
  LICENSE-Part-2.jpg
  LICENSE-Part-3.jpg
Labels: enhancement/other

#780 Add MountBypass
  src/main/java/me/zeroeightsix/kami/module/modules/misc/MountBypass.java
Labels: new/module

#783 Added macros
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/ConfigCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/MacroCommand.kt
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinMinecraft.java
  src/main/java/me/zeroeightsix/kami/module/MacroManager.kt
  src/main/java/me/zeroeightsix/kami/module/Macros.java
  src/main/java/me/zeroeightsix/kami/util/Macro.kt
  src/main/java/me/zeroeightsix/kami/util/MessageSendHelper.java
  src/main/java/me/zeroeightsix/kami/util/Wrapper.java
Labels: new/other

#782 InventoryMove: Fix AAC kick from pitch overflows
  src/main/java/me/zeroeightsix/kami/gui/kami/DisplayGuiScreen.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/InventoryMove.kt
Labels: bug/module, enhancement/module

#781 AutoRemount now works with other mountable entities
  src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoRemount.java
Labels: enhancement/module

#805 Change from mc.theWorld to chunk
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java
Labels: enhancement/module

#757 Add coordinate log command and improved the CoordUtil
  src/main/java/me/zeroeightsix/kami/command/commands/CoordsCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/SearchCommand.java
  src/main/java/me/zeroeightsix/kami/module/modules/experimental/CoordsLog.java
  src/main/java/me/zeroeightsix/kami/module/modules/hidden/CoordsLog.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java
  src/main/java/me/zeroeightsix/kami/util/CoordUtil.java
  src/main/java/me/zeroeightsix/kami/util/Coordinate.java
  src/main/java/me/zeroeightsix/kami/util/CoordinateInfo.java
  src/main/java/me/zeroeightsix/kami/util/LogUtil.java
Labels: enhancement/other, new/module

#804 Added a 'Log To File' to the VisualRange module.
  src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt
Labels: enhancement/module

#806 Added '.build()' calls to settings lacking this call.
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatFilter.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoMend.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/PacketCancel.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/HungerOverlay.kt
Labels: bug/module

#807 Added the option to look for droppers and dispensers in stashfinder.
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
Labels: enhancement/module

#812 Hide doLocale setting when in H24 timeunit mode.
  src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java
Labels: enhancement/gui

#813 Implemented the same 'hidden doLocale' for the chatTimestamp module.
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatTimestamp.kt
Labels: enhancement/module

#815 Fixed an error being raised in 'all' fastuse mode while the player is a spectator.
  src/main/java/me/zeroeightsix/kami/module/modules/player/Fastuse.kt
Labels: bug/module

#833 Improved Aura and fixed a bug with Packet Cancel
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/PacketCancel.kt
Labels: bug/module, enhancement/module

#826 Some updates to the AntiSpam module.
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.kt
Labels: 03-testing-pending, bug/module, enhancement/module

#825 Fix Spammer doesn't support cyrillic symbols
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatFilter.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/LoginMessage.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.java
Labels: 03-testing-pending, bug/module

#817 FastUse bow bugfix and feature implementation.
  src/main/java/me/zeroeightsix/kami/module/modules/player/Fastuse.kt
Labels: 03-testing-pending, bug/module, enhancement/module

#811 Fixing problems with friends.
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
Labels: 03-testing-pending, bug/module, enhancement/gui

#847 Added a 'biome' setting to the info overlay.
  src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java
Labels: 03-testing-pending, enhancement/gui

#844 Fixed stash list command regex, added IDs to CoordinateInfo
  src/main/java/me/zeroeightsix/kami/command/commands/CoordsCommand.java
  src/main/java/me/zeroeightsix/kami/util/CoordinateInfo.java
Labels: 02-review-pending, enhancement/other

#837 Added Baritone and improved AutoWalk, and removed Pathfind
  build.gradle
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/BaritoneCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/PathCommand.java
  src/main/java/me/zeroeightsix/kami/command/syntax/parsers/BaritoneParser.java
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.java
  src/main/java/me/zeroeightsix/kami/mixin/MixinLoaderForge.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiIngameMenu.java
  src/main/java/me/zeroeightsix/kami/module/modules/client/Baritone.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/hidden/RunConfig.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoWalk.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoWalk.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/LagNotifier.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Pathfind.java
  src/main/java/me/zeroeightsix/kami/process/TemporaryPauseProcess.java
  src/main/java/me/zeroeightsix/kami/util/BaritoneUtils.kt
  src/main/java/me/zeroeightsix/kami/util/MathsUtils.java
  src/main/java/me/zeroeightsix/kami/util/MessageSendHelper.java
Labels: 01-changes-requested, new/gui, new/module, new/other

#857 Fixed fullbright only working if transition is on.
  src/main/java/me/zeroeightsix/kami/module/modules/render/Brightness.java
Labels: 03-testing-pending, bug/module

#866 Some ElytraReplace changes.
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraReplace.kt
Labels: 01-info-requested, bug/module, enhancement/module

#876 Fix customsize #tunnel if AutoTunnel settings are default
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTunnel.kt
Labels: bug/module

#879 Fixed autoeat eating pufferfish, issue #875
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt
Labels: 03-testing-pending, bug/module

#897 Added AntiZispanos
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.kt
Labels: enhancement/module

#908 Ignore friends option for VisualRange
  src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt
Labels: 01-changes-requested, enhancement/module
