Repository kami-blue/client, pull requests merged in 2020-09, with the labels that each got.

#1310 Rewrote Chams and made it more customizable
  src/main/java/me/zeroeightsix/kami/event/KamiEvent.kt
  src/main/java/me/zeroeightsix/kami/event/events/RenderEntityEvent.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderLiving.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderManager.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Chams.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/resources/mixins.kami.json
Labels: -module, -other, enhancement, new

#1311 Rewrote PlayerPacketManger mixins
  src/main/java/me/zeroeightsix/kami/manager/mangers/PlayerPacketManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
Labels: --testing-pending, -other, bug

#1314 PingSpoof
  src/main/java/me/zeroeightsix/kami/module/modules/misc/PingSpoof.kt
Labels: --testing-pending, -module, new

#1309 Made EntitySpeed flight option works for boat, added primary passenger check
  src/main/java/me/zeroeightsix/kami/module/modules/movement/EntitySpeed.kt
Labels: --testing-pending, -module, bug

#1294 Antioverlay Improvements
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityRenderer.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/AntiOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/AntiOverlay.kt
Labels: --changes-requested, -module, -other, enhancement

#1339 Fixed BreakingESP and LoginMessage
  src/main/java/me/zeroeightsix/kami/module/modules/chat/LoginMessage.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/BreakingESP.kt
Labels: -module, bug, enhancement

#1350 Improved Waypoints and optimized code
  src/main/java/me/zeroeightsix/kami/command/commands/WaypointCommand.kt
  src/main/java/me/zeroeightsix/kami/event/events/WaypointUpdateEvent.kt
  src/main/java/me/zeroeightsix/kami/manager/ManagerLoader.kt
  src/main/java/me/zeroeightsix/kami/manager/mangers/FileInstanceManager.kt
  src/main/java/me/zeroeightsix/kami/manager/mangers/WaypointManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoRespawn.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/CoordsLog.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/LogoutLogger.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/TeleportLogger.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt
  src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
  src/main/java/me/zeroeightsix/kami/util/Waypoint.kt
  src/main/java/me/zeroeightsix/kami/util/WaypointInfo.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/TextComponent.kt
  src/main/java/me/zeroeightsix/kami/util/math/CoordinateConverter.kt
  src/main/java/me/zeroeightsix/kami/util/math/VectorUtils.kt
Labels: --changes-requested, -module, bug, enhancement

#1359 NameTags rewrite
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinRender.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderPlayer.java
  src/main/java/me/zeroeightsix/kami/module/modules/client/ActiveModules.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.kt
  src/main/java/me/zeroeightsix/kami/util/EnchantmentUtils.kt
  src/main/java/me/zeroeightsix/kami/util/color/ColorGradient.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/TextComponent.kt
  src/main/resources/mixins.kami.json
Labels: --changes-requested, -module, bug, enhancement

#1375 Rewrote Freecam
  detekt.yml
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntity.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinFrustum.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinMovementInputFromOptions.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderPlayer.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoFeetPlace.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTunnel.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoWalk.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Jesus.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/java/me/zeroeightsix/kami/util/math/MathUtils.kt
Labels: --review-pending, -module, enhancement
