Repository kami-blue/client, pull requests merged in 2020-07, with the labels that each got.

#1003 Lots of improvements and rewrite of ElytraFlight
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/LagNotifier.kt
  src/main/java/me/zeroeightsix/kami/process/TemporaryPauseProcess.java
Labels: 01-info-requested, enhancement/module

#1011 Add hunger, speed, helditem, fps, tps options to DiscordRPC
  src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordRPC.kt
Labels: 01-changes-requested, enhancement/module

#1012 Added actual hypixel messages to AutoEZ
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.kt
Labels: enhancement/module

#1029 Fixed inventory viewer height & added blue to fancychat
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FancyChat.kt
Labels: enhancement/gui, enhancement/module

#1024 Added AutoExcuse(#840)
  .gitignore
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
Labels: 02-review-pending, new/module

#1023 Improved ElytraFlight and moved Surround calcs to a util
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/java/me/zeroeightsix/kami/util/CenterPlayer.kt
Labels: 00-blocked, 01-changes-requested, bug/module, enhancement/module, new/other

#1031 Combat modules update
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Criticals.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Chams.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtil.java
  src/main/java/me/zeroeightsix/kami/util/EntityUtil.kt
Labels: 02-review-pending, bug/module, enhancement/module

#1039 No separator when one field is empty in DiscordRPC module
  src/main/java/me/zeroeightsix/kami/DiscordPresence.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordRPC.kt
Labels: 01-changes-requested, enhancement/module

#1050 Updated website link
  src/main/java/me/zeroeightsix/kami/module/modules/chat/CustomChat.kt
Labels: bug/module

#1064 Added InventoryManger, Auto Obsidian and some bug fixes
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/EjectCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/EntityStatsCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/SetBuildingBlockCommand.kt
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.java
  src/main/java/me/zeroeightsix/kami/module/ModuleManager.java
  src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoFeetPlace.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoReplenish.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Criticals.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoObsidian.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoSpawner.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordRPC.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoWalk.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/EntitySpeed.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Flight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Jesus.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Fastbreak.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/LagNotifier.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/NoFall.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Chams.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/EyeFinder.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/MobOwner.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
  src/main/java/me/zeroeightsix/kami/process/AutoObsidianProcess.kt
  src/main/java/me/zeroeightsix/kami/process/TemporaryPauseProcess.java
  src/main/java/me/zeroeightsix/kami/process/TemporaryPauseProcess.kt
  src/main/java/me/zeroeightsix/kami/util/BaritoneUtils.kt
  src/main/java/me/zeroeightsix/kami/util/BlockInteractionHelper.java
  src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt
Labels: 03-testing-pending, enhancement/module, new/module

#1074 Added Step
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Step.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/java/me/zeroeightsix/kami/util/PacketHelper.java
Labels: 02-review-pending, new/module

#1075 Add ShowHidden option to ActiveModules
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/client/ActiveModules.java
Labels: 03-testing-pending, enhancement/gui
