Repository kami-blue/client, pull requests merged in 2020-06, with the labels that each got.

#886 Added Module MapPreview see issue #143
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinGuiScreen.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/MapPreview.kt
Labels: 03-testing-pending, new/module

#896 Fixed Look Boost working when not moving
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
Labels: 03-testing-pending, enhancement/module

#939 Added option for tracers for StorageESP and Search #619
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/StorageESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
  src/main/java/me/zeroeightsix/kami/util/KamiTessellator.java
Labels: 03-testing-pending

#961 Added elytra check, issue #881
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
Labels: bug/module

#985 Adding packet mode to fastbreak, issue #796
  src/main/java/me/zeroeightsix/kami/module/modules/player/Fastbreak.kt
Labels: 03-testing-pending, enhancement/module

#982 Added delay mode to Criticals
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Criticals.kt
Labels: 03-testing-pending

#984 Kotlinized Player modules and fixed issues #983, #971
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinPlayerControllerMP.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/InventoryMove.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/AntiForceLook.java
  src/main/java/me/zeroeightsix/kami/module/modules/player/AntiForceLook.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoArmour.java
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoArmour.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/NoBreakAnimation.java
  src/main/java/me/zeroeightsix/kami/module/modules/player/NoBreakAnimation.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/PacketLogger.java
  src/main/java/me/zeroeightsix/kami/module/modules/player/PacketLogger.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/TpsSync.java
  src/main/java/me/zeroeightsix/kami/module/modules/player/TpsSync.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ChunkFinder.java
Labels: 01-changes-requested, enhancement/other

#974 Greatly improved ElytraFlight and added Space trigger
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
Labels: 01-changes-requested, bug/module, enhancement/module
