Repository kami-blue/client, pull requests merged in 2020-11, with the labels that each got.

#1543 [feature] EatBadFood setting for the AutoEat module
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt
Labels: --changes-requested, -module, enhancement

#1539 [feature] Added HideOwn option to HoleESP
  src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleESP.kt
Labels: --testing-pending, -module, enhancement

#1565 [fix] Flight crash in singleplayer
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Flight.kt
Labels: -module, bug

#1569 Added some more hypixel ez
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.kt
Labels: --changes-requested, -module, enhancement

#1574 [enhancement] Added more excuses to AutoExcuse
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
Labels: --changes-requested, -module, enhancement

#1579 Improve AutoExcuse
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
Labels: -module, enhancement

#1589 Color change range for Tracers
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
Labels: --review-pending, -module, enhancement

#1583 [fix] Removed ChunkSize to fix weird invisible entities bug
  src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.kt
  src/main/java/me/zeroeightsix/kami/util/InfoCalculator.kt
  src/main/resources/kami_at.cfg
Labels: --review-pending, -module, bug

#1598 [enhancement] colorChangeRange should only appear if rangedColor is selected on the Tracers module
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
Labels: --review-pending, -module, enhancement

#1600 Added sound to FriendHighlight.
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
Labels: --testing-pending, -module, enhancement

#1594 [feature] Added ViewLock, replaces *lock
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinEntityRenderer.java
  src/main/java/me/zeroeightsix/kami/module/modules/player/PitchLock.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/ViewLock.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/YawLock.kt
Labels: --changes-requested, -module, enhancement

#1531 [feature] NoRender rewrite
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinMapItemRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinParticleManager.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinTileEntityEnchantmentTableRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinTileEntityRendererDispatcher.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt
  src/main/resources/assets/minecraft/kamiblue/kamimap.png
  src/main/resources/kami_at.cfg
  src/main/resources/mixins.kami.json
Labels: --review-pending, -module, bug, enhancement

#1619 [cleanup] Minecraft#displayGuiScreen Mixin
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinMinecraft.java
Labels: --testing-pending, -other, enhancement

#1630 [bump] Kotlin to 1.3.72
  gradle.properties
Labels: --review-pending, -dependencies

#1644 Fix freecam chunk rendering
  src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
Labels: --info-requested, -module, enhancement

#1643 [feature] Censor option for BossStack
  src/main/java/me/zeroeightsix/kami/module/modules/render/BossStack.kt
Labels: -module, enhancement

#1646 [feature] Add manual mode to automine.
  src/main/java/me/zeroeightsix/kami/mixin/client/accessor/AccessorMinecraft.java
  src/main/java/me/zeroeightsix/kami/mixin/extension/Misc.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoMine.kt
Labels: --review-pending, -module, enhancement
