Repository kami-blue/client, pull requests merged in 2020-12, with the labels that each got.

#1652 [feature] Default setting button for everything
  src/main/java/me/zeroeightsix/kami/command/commands/SetCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/SettingsCommand.java
  src/main/java/me/zeroeightsix/kami/command/syntax/parsers/ValueParser.java
  src/main/java/me/zeroeightsix/kami/gui/kami/component/SettingsPanel.java
  src/main/java/me/zeroeightsix/kami/module/Module.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoFish.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt
  src/main/java/me/zeroeightsix/kami/setting/Setting.java
Labels: --testing-pending, -module, enhancement

#1653 [cleanup] Cleaned up ColorTextFormatting
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatTimestamp.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/ActiveModules.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/InfoOverlay.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/TotemPopCounter.kt
  src/main/java/me/zeroeightsix/kami/util/color/ColorTextFormatting.kt
  src/main/java/me/zeroeightsix/kami/util/color/EnumTextColor.kt
Labels: --testing-pending, -module, enhancement

#1651 [fix] Freecam movement input compatibility
  src/main/java/me/zeroeightsix/kami/mixin/client/player/MixinMovementInputFromOptions.java
  src/main/java/me/zeroeightsix/kami/module/modules/movement/AutoWalk.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/InventoryMove.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
  src/main/resources/mixins.kami.json
Labels: --review-pending, -module, bug

#1650 [feature] Added DirectionMode to Freecam
  src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
Labels: --testing-pending, -module, enhancement

#1656 Added NewChunks to the Radar and improved unloading of NewChunks
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/NewChunks.kt
Labels: --review-pending, -gui, enhancement

#1661 [enhancement] Enum setting displaying
  src/main/java/me/zeroeightsix/kami/gui/kami/component/SettingsPanel.java
  src/main/java/me/zeroeightsix/kami/gui/kami/component/SettingsPanel.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
Labels: --review-pending, -gui, -module, enhancement

#1664 [refactor] Updated Gradle and bunch of dependencies
  .travis.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  scripts/buildJarSafe.sh
  scripts/buildNamed.sh
  scripts/bumpMajor.sh
  scripts/bumpVersion.sh
  scripts/runAutomatedRelease.sh
  scripts/setupWorkspace.sh
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinRenderPlayer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinTileEntitySignRenderer.java
  src/main/resources/ascii.txt
  src/main/resources/darwin/libdiscord-rpc.dylib
  src/main/resources/kami_at.cfg
  src/main/resources/linux-x86-64/libdiscord-rpc.so
  src/main/resources/mcmod.info
  src/main/resources/win32-x86-64/discord-rpc.dll
  src/main/resources/win32-x86/discord-rpc.dll
Labels: --review-pending, -building, -dependencies, enhancement

#1743 [feature] Added Github Actions
  .github/workflows/gradle_build.yml
  .travis.yml
Labels: --review-pending

#1753 [cleanup] Cleaned up Macro
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/MacroCommand.kt
  src/main/java/me/zeroeightsix/kami/manager/ManagerLoader.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/FileInstanceManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/MacroManager.kt
  src/main/java/me/zeroeightsix/kami/util/Macro.kt
Labels: --review-pending, -module, enhancement

#1515 [feature] Culling for StorageESP
  src/main/java/me/zeroeightsix/kami/module/modules/render/StorageESP.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/ESPRenderer.kt
Labels: -module, enhancement

#1758 Fix not unpausing even though control is lost
  src/main/java/me/zeroeightsix/kami/util/BaritoneUtils.kt
Labels: --testing-pending, -other, bug

#1760 [enhancement] Scaffold
  src/main/java/me/zeroeightsix/kami/command/ExecuteEvents.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/PlayerPacketManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/entity/MixinEntity.java
  src/main/java/me/zeroeightsix/kami/module/Module.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt
  src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
  src/main/java/me/zeroeightsix/kami/util/math/VectorUtils.kt
Labels: --review-pending, -module, enhancement

#1770 [cleanup] Rewrote message detection
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoReply.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoTPA.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/BaritoneRemote.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatFilter.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/CustomChat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/DiscordNotifs.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FancyChat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/LoginMessage.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
  src/main/java/me/zeroeightsix/kami/util/text/Detectors.kt
  src/main/java/me/zeroeightsix/kami/util/text/MessageDetection.kt
  src/main/java/me/zeroeightsix/kami/util/text/MessageDetectionHelper.kt
Labels: --review-pending, -module, enhancement

#1768 [cleanup] Switch to Coroutines
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/Loader.kt
  src/main/java/me/zeroeightsix/kami/command/ClientCommand.kt
  src/main/java/me/zeroeightsix/kami/command/CommandManager.kt
  src/main/java/me/zeroeightsix/kami/command/commands/ConfigCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/GenerateWebsiteCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/NBTCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/PeekCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/WaypointCommand.kt
  src/main/java/me/zeroeightsix/kami/event/ClientEvents.kt
  src/main/java/me/zeroeightsix/kami/event/KamiEventBus.kt
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiChat.kt
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiDisconnected.kt
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiUpdateNotification.kt
  src/main/java/me/zeroeightsix/kami/manager/ManagerLoader.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/KamiMojiManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinFontRenderer.java
  src/main/java/me/zeroeightsix/kami/module/Module.kt
  src/main/java/me/zeroeightsix/kami/module/ModuleManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/Capes.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/CommandConfig.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/CustomFont.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CombatSetting.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/DiscordRPC.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/MidClickFriends.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/FastBreak.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/NoFall.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt
  src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
  src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
  src/main/java/me/zeroeightsix/kami/util/CoroutineUtils.kt
  src/main/java/me/zeroeightsix/kami/util/threads/BackgroundJob.kt
  src/main/java/me/zeroeightsix/kami/util/threads/BackgroundScope.kt
  src/main/java/me/zeroeightsix/kami/util/threads/CoroutineUtils.kt
  src/main/java/me/zeroeightsix/kami/util/threads/ThreadSafety.kt
Labels: --review-pending, -module, enhancement

#1775 [new] NoteBot
  src/main/java/me/zeroeightsix/kami/module/modules/misc/NoteBot.kt
  src/main/java/me/zeroeightsix/kami/util/threads/ThreadSafety.kt
Labels: -module, new

#1777 [enhancement] Improve ChatEncryption module
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatEncryption.kt
Labels: --review-pending, -module, enhancement

#1759 [fix] Freecam renderbugs
  src/main/java/me/zeroeightsix/kami/mixin/client/accessor/render/AccessorViewFrustum.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinRenderGlobal.java
  src/main/java/me/zeroeightsix/kami/mixin/extension/Render.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
  src/main/resources/mixins.kami.json
Labels: --testing-pending, -module, bug
