Repository kami-blue/client, pull requests merged in 2020-02, with the labels that each got.

#426 Close #329
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InfoOverlay.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/ChatTimestamp.java
  src/main/java/me/zeroeightsix/kami/util/ColourUtils.java
  src/main/java/me/zeroeightsix/kami/util/InfoCalculator.java
  src/main/java/me/zeroeightsix/kami/util/TimeUtil.java
Labels: 4 - Done, gui/enhancement, module/new-feature

#436 Don't run prefixchat when sneaking
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.java
Labels: gui/bug

#441 Textradar StrengthDetect
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/StrengthDetect.java
Labels: gui/enhancement, module/new-feature

#448 Add in overrides to getValueAsString/setValueFromString so string set…
  src/main/java/me/zeroeightsix/kami/setting/impl/StringSetting.java
Labels: module/bug

#457 Update branch for testing
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/Command.java
  src/main/java/me/zeroeightsix/kami/command/commands/CustomChatCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/NBTCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/SignBookCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/XRayCommand.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinChunkCache.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/CustomChat.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/XRay.java
  src/main/resources/assets/kamiblue/blockstates/kami_xray_transparent.json
  src/main/resources/assets/kamiblue/models/block/kami_xray_transparent.json
  src/main/resources/assets/kamiblue/textures/blocks/kami_xray_transparent.png
  src/main/resources/mixins.kami.json
Labels: -meta

#458 [Fix] Enum Setting
  src/main/java/me/zeroeightsix/kami/setting/converter/EnumConverter.java
  src/main/java/me/zeroeightsix/kami/setting/impl/EnumSetting.java
Labels: bug/other

#473 Add color options to Inventory Preview and clean up modes
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/RenderHelper.java
  src/main/java/me/zeroeightsix/kami/module/modules/gui/InventoryViewer.java
  src/main/java/me/zeroeightsix/kami/util/KamiTessellator.java
  src/main/resources/assets/minecraft/kamiblue/clear.png
  src/main/resources/assets/minecraft/kamiblue/large.png
  src/main/resources/assets/minecraft/kamiblue/medium.png
  src/main/resources/assets/minecraft/kamiblue/small.png
  src/main/resources/assets/minecraft/textures/gui/container/four.png
  src/main/resources/assets/minecraft/textures/gui/container/one.png
  src/main/resources/assets/minecraft/textures/gui/container/six.png
  src/main/resources/assets/minecraft/textures/gui/container/three.png
  src/main/resources/assets/minecraft/textures/gui/container/two.png
Labels: enhancement/module

#476 Feature/offhandgap#356
  src/main/java/me/zeroeightsix/kami/module/modules/combat/OffhandGap.java
Labels: new/module

#489 Add hypixel to antispam lol
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java
Labels: enhancement/module, review-pending
