Repository kami-blue/client, pull requests merged in 2020-10, with the labels that each got.

#1238 [enhancement] Added input timeout option to AntiAFK
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoReply.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
Labels: --changes-requested, -blocked, -module, enhancement

#1406 Update README.md
  README.md
Labels: -other, enhancement

#1407 typo in antibot
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiBot.kt
Labels: bug

#1335 [feature] Combat update
  detekt.yml
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.kt
  src/main/java/me/zeroeightsix/kami/event/KamiEvent.kt
  src/main/java/me/zeroeightsix/kami/event/events/ClientPlayerAttackEvent.kt
  src/main/java/me/zeroeightsix/kami/event/events/RenderEntityEvent.kt
  src/main/java/me/zeroeightsix/kami/manager/mangers/CombatManager.kt
  src/main/java/me/zeroeightsix/kami/manager/mangers/PlayerPacketManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinMinecraft.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinPlayerControllerMP.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinRenderManager.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiChainPop.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiFriendHit.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoFeetPlace.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoLog.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoOffhand.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTotem.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/BedAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CombatSetting.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleMiner.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleSnap.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/OffhandGap.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTool.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/EyeFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
  src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
  src/main/java/me/zeroeightsix/kami/util/CenterPlayer.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt
  src/main/java/me/zeroeightsix/kami/util/MotionTracker.kt
  src/main/java/me/zeroeightsix/kami/util/combat/CombatUtils.kt
  src/main/java/me/zeroeightsix/kami/util/combat/CrystalUtils.kt
  src/main/java/me/zeroeightsix/kami/util/combat/SurroundUtils.kt
  src/main/java/me/zeroeightsix/kami/util/math/RotationUtils.kt
  src/main/java/me/zeroeightsix/kami/util/math/Vec2d.kt
  src/main/java/me/zeroeightsix/kami/util/math/Vec2f.kt
Labels: --changes-requested, -module, enhancement, new

#1425 [feature] Shader ESP
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt
  src/main/resources/assets/minecraft/shaders/post/esp_outline.json
  src/main/resources/assets/minecraft/shaders/program/esp_outline.fsh
  src/main/resources/assets/minecraft/shaders/program/esp_outline.json
Labels: -module, new

#1450 [cleanup] Removed unused dependencies
  build.gradle
Labels: --review-pending, -dependencies, enhancement

#1457 [feature] Added hoppers to Stashfinder
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
Labels: -module, enhancement

#1475 [feature] CrystalBasePlace and CrystalAura enhancements
  src/main/java/me/zeroeightsix/kami/manager/mangers/CombatManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CombatSetting.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalBasePlace.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalESP.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/java/me/zeroeightsix/kami/util/MotionTracker.kt
  src/main/java/me/zeroeightsix/kami/util/Quad.kt
  src/main/java/me/zeroeightsix/kami/util/combat/CrystalUtils.kt
  src/main/java/me/zeroeightsix/kami/util/math/RotationUtils.kt
Labels: --review-pending, -module, enhancement, new

#1488 [feature] Enchanting Table books option for NoRender
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinNetHandlerPlayClient.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinTileEntityEnchantmentTableRenderer.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt
  src/main/resources/mixins.kami.json
Labels: --review-pending, -module, enhancement

#1487 [feature] Custom excuse options for AutoExcuse
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
Labels: --changes-requested, -module, enhancement

#1496 [feature] Player Inventory Manager
  src/main/java/me/zeroeightsix/kami/manager/mangers/CombatManager.kt
  src/main/java/me/zeroeightsix/kami/manager/mangers/PlayerInventoryManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoArmor.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/BedAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalBasePlace.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleMiner.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
  src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt
Labels: --review-pending, -module, bug, new

#1497 [feature] Message Manager
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/command/commands/CustomChatCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/FakeMessageCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/LicenseCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/SayCommand.java
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiPotionUi.kt
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.java
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiUpdateNotification.java
  src/main/java/me/zeroeightsix/kami/manager/managers/MessageManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/PlayerInventoryManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntityPlayerSP.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoExcuse.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatEncryption.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/CustomChat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FancyChat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FormatChat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/ChatSetting.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoArmor.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/ColorSign.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/TabFriends.kt
  src/main/java/me/zeroeightsix/kami/util/TaskState.kt
  src/main/java/me/zeroeightsix/kami/util/text/MessageDetectionHelper.kt
  src/main/java/me/zeroeightsix/kami/util/text/MessageSendHelper.kt
Labels: --review-pending, -module, enhancement, new

#1498 [enhancement] Rewrote Friends
  src/main/java/me/zeroeightsix/kami/command/commands/FriendCommand.kt
  src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/staticui/RadarUI.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/FileInstanceManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/FriendManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/WaypointManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/AutoTPA.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/BaritoneRemote.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/FriendHighlight.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiFriendHit.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoLog.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/TotemPopCounter.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/MidClickFriends.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/TabFriends.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
  src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/java/me/zeroeightsix/kami/util/Friends.kt
Labels: --testing-pending, -module, enhancement

#1501 [cleanup] [feature] Cleanup utils, added 2 block step
  src/main/java/me/zeroeightsix/kami/command/commands/WaypointCommand.kt
  src/main/java/me/zeroeightsix/kami/event/events/WaypointUpdateEvent.kt
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiPotionUi.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/KamiMojiManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/PlayerInventoryManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/PlayerPacketManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/WaypointManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinPlayerControllerMP.java
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Step.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/WaypointRender.kt
  src/main/java/me/zeroeightsix/kami/util/BetterArrayList.kt
  src/main/java/me/zeroeightsix/kami/util/InfoCalculator.kt
  src/main/java/me/zeroeightsix/kami/util/JsonUtils.kt
  src/main/java/me/zeroeightsix/kami/util/PacketHelper.kt
  src/main/java/me/zeroeightsix/kami/util/TpsCalculator.kt
  src/main/java/me/zeroeightsix/kami/util/Waypoint.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/KamiTessellator.kt
Labels: --review-pending, -module, -other, enhancement

#1507 [feature] Added Norender option for signtext
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinTileEntitySignRenderer.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt
  src/main/resources/mixins.kami.json
Labels: --testing-pending, -module, enhancement

#1514 [fix] Bug with AntiWeather
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinWorld.java
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiWeather.kt
Labels: --changes-requested, -module, bug

#1518 [fix] Fix Autoreconnect and AntiAfk bug
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoReconnect.kt
Labels: --changes-requested, -module, bug, enhancement

#1499 [fix] Framebuffer creation issues causing black screens
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/ShaderHelper.kt
Labels: --changes-requested, -other, bug

#1523 [enhancement] Optimized Module loading and cleaned up code
  src/main/java/me/zeroeightsix/kami/command/CommandManager.java
  src/main/java/me/zeroeightsix/kami/command/commands/BindCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/HelpCommand.java
  src/main/java/me/zeroeightsix/kami/command/commands/ToggleCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/TroubleshootCommand.java
  src/main/java/me/zeroeightsix/kami/gui/kami/DisplayGuiScreen.java
  src/main/java/me/zeroeightsix/kami/gui/kami/theme/kami/KamiActiveModulesUI.java
  src/main/java/me/zeroeightsix/kami/manager/ManagerLoader.kt
  src/main/java/me/zeroeightsix/kami/module/Module.kt
  src/main/java/me/zeroeightsix/kami/module/ModuleManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/ClickGUI.kt
  src/main/java/me/zeroeightsix/kami/module/modules/hidden/FixGui.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/XRay.java
  src/main/java/me/zeroeightsix/kami/util/ClassFinder.kt
  src/main/java/me/zeroeightsix/kami/util/ClassUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/TextComponent.kt
Labels: --review-pending, -module, enhancement

#1526 [feature] Created VoidESP
  src/main/java/me/zeroeightsix/kami/module/modules/render/VoidESP.kt
Labels: --changes-requested, -module, new
