Repository kami-blue/client, pull requests merged in 2021-02, with the labels that each got.

#1890 [fix] AutoMend should only try to mend when near blocks
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoMend.kt
Labels: --testing-pending, -module, bug

#1894 [fix] F3 Debug Pie would crash on Single Player
  src/main/java/me/zeroeightsix/kami/mixin/client/player/MixinEntityPlayer.java
Labels: --testing-pending, -other, bug

#1897 [fix] Move all configs to `kamiblue` folder
  src/main/java/me/zeroeightsix/kami/manager/managers/FriendManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/MacroManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/WaypointManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ChatFilter.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/Spammer.kt
  src/main/java/me/zeroeightsix/kami/util/ConfigUtils.kt
Labels: -other, enhancement

#1884 [cleanup] Switch to OkHttp from dumb http libraries
  build.gradle
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/DiscordNotifs.kt
Labels: -dependencies, -module, enhancement

#1899 [cleanup] Removed bloat http request lib
  build.gradle
  src/main/java/me/zeroeightsix/kami/KamiMod.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/DiscordNotifs.kt
Labels: -dependencies, -module, enhancement

#1900 [cleanup] ChunkEvent, NoRender, NewChunks
  src/main/java/me/zeroeightsix/kami/event/events/ChunkEvent.kt
  src/main/java/me/zeroeightsix/kami/event/events/PacketEvent.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/network/MixinNetHandlerPlayClient.java
  src/main/java/me/zeroeightsix/kami/mixin/client/network/MixinNetworkManager.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinTileEntityRendererDispatcher.java
  src/main/java/me/zeroeightsix/kami/module/modules/render/NewChunks.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt
  src/main/resources/mixins.kami.json
Labels: --review-pending, -module, enhancement

#1905 [new] Implemented non blocking main thread execution with deferred callback
  src/main/kotlin/org/kamiblue/client/command/CommandManager.kt
  src/main/kotlin/org/kamiblue/client/module/modules/client/CustomFont.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/FakePlayer.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/LogoutLogger.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/StashLogger.kt
  src/main/kotlin/org/kamiblue/client/module/modules/player/Freecam.kt
  src/main/kotlin/org/kamiblue/client/module/modules/render/NewChunks.kt
  src/main/kotlin/org/kamiblue/client/util/items/Operation.kt
  src/main/kotlin/org/kamiblue/client/util/threads/MainThreadExecutor.kt
  src/main/kotlin/org/kamiblue/client/util/threads/ThreadSafety.kt
Labels: --review-pending, -other, new

#1908 Bumped a few urls to https
  build.gradle
Labels: -dependencies, -other, enhancement

#1906 [feature] Added `.nbs` support to Notebot
  src/main/kotlin/org/kamiblue/client/module/modules/misc/NoteBot.kt
Labels: --changes-requested, -module, enhancement

#1912 [enhancement] Add CPS to the HUD
  src/main/java/org/kamiblue/client/mixin/client/MixinMinecraft.java
  src/main/kotlin/org/kamiblue/client/event/events/MouseClickEvent.kt
  src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/CPS.kt
Labels: --changes-requested, -gui, enhancement

#1911 [feature] Add default button to hud elements
  src/main/kotlin/org/kamiblue/client/gui/hudgui/HudElement.kt
Labels: -gui, enhancement

#1913 [enhancement] Add color bar to Armor
  src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/combat/Armor.kt
Labels: --changes-requested, -gui, enhancement

#1921 [enhancement] Use ChunkPos instead of Chunk in NewChunks
  src/main/kotlin/org/kamiblue/client/module/modules/render/NewChunks.kt
Labels: -module, enhancement

#1920 [enhancement] Add SmallShield alias to ItemModel for discoverability
  src/main/kotlin/org/kamiblue/client/module/modules/render/ItemModel.kt
Labels: -module, enhancement

#1922 [enhancement] Add in Speed modifiers into Strafe
  src/main/kotlin/org/kamiblue/client/module/modules/movement/Strafe.kt
  src/main/kotlin/org/kamiblue/client/util/MovementUtils.kt
Labels: -module, enhancement

#1926 [enhancement] rename save to file to save to waypoints
  src/main/kotlin/org/kamiblue/client/module/modules/misc/StashLogger.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/TeleportLogger.kt
Labels: -module, enhancement

#1919 [feature] AutoOffHand adjustable delay
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoOffhand.kt
Labels: --testing-pending, -module, enhancement

#1931 [refactor] Converted KamiMod to Kotlin
  src/main/java/org/kamiblue/client/KamiMod.java
  src/main/kotlin/org/kamiblue/client/KamiMod.kt
  src/main/kotlin/org/kamiblue/client/gui/rgui/Component.kt
  src/main/kotlin/org/kamiblue/client/util/Wrapper.kt
Labels: --testing-pending, -other, enhancement

#1934 [enhancement] Refactor TPS/FPS Calculation
  src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/FPS.kt
  src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/TPS.kt
  src/main/kotlin/org/kamiblue/client/module/modules/client/Capes.kt
  src/main/kotlin/org/kamiblue/client/util/CircularArray.kt
  src/main/kotlin/org/kamiblue/client/util/TpsCalculator.kt
Labels: --testing-pending, -module, enhancement

#1925 [enhancement] Add a modified setting command.
  src/main/kotlin/org/kamiblue/client/command/commands/ModifiedCommand.kt
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/BindButton.kt
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/EnumSlider.kt
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/SettingButton.kt
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/SettingSlider.kt
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/Slider.kt
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/StringButton.kt
  src/main/kotlin/org/kamiblue/client/module/modules/client/ClickGUI.kt
  src/main/kotlin/org/kamiblue/client/setting/settings/AbstractSetting.kt
  src/main/kotlin/org/kamiblue/client/util/text/MessageSendHelper.kt
Labels: --testing-pending, -gui, enhancement

#1928 [cleanup] Cleaned up crystal damage calculations
  src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/combat/CrystalDamage.kt
  src/main/kotlin/org/kamiblue/client/manager/managers/CombatManager.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoLog.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoOffhand.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CombatSetting.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalAura.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalBasePlace.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalESP.kt
  src/main/kotlin/org/kamiblue/client/util/combat/CrystalUtils.kt
Labels: --changes-requested, -module, enhancement

#1939 [enhancement] Added binds to HUD elements.
  src/main/kotlin/org/kamiblue/client/event/ForgeEventProcessor.kt
  src/main/kotlin/org/kamiblue/client/gui/GuiManager.kt
  src/main/kotlin/org/kamiblue/client/gui/hudgui/HudElement.kt
Labels: -gui, enhancement

#1949 [fix] Use Baritone's helper to log messages
  src/main/kotlin/org/kamiblue/client/util/text/MessageSendHelper.kt
Labels: --testing-pending, -other, enhancement

#2086 [fix] wrong message being displayed when adding friends.
  src/main/kotlin/org/kamiblue/client/module/modules/misc/MidClickFriends.kt
Labels: -other, bug
