Repository kami-blue/client, pull requests merged in 2021-01, with the labels that each got.

#1781 [fix] Gradle for macOS
  build.gradle
Labels: --testing-pending, -other, bug

#1782 [fix] Freecam kills fps
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinFrustum.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinRenderGlobal.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinVisGraph.java
  src/main/resources/mixins.kami.json
Labels: --review-pending, -module, enhancement

#1790 [enhancement] Add dolphin mode to Jesus (#1178)
  src/main/java/me/zeroeightsix/kami/module/modules/movement/Jesus.kt
Labels: --changes-requested, -module, enhancement

#1799 [feature] Baritone AutoComplete
  src/main/java/me/zeroeightsix/kami/command/Args.kt
  src/main/java/me/zeroeightsix/kami/command/ClientCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/BaritoneCommand.kt
  src/main/java/me/zeroeightsix/kami/util/text/MessageSendHelper.kt
Labels: -module, enhancement

#1806 [enhancement] Added EntityList, TextRadar, WorldTime
  src/main/java/me/zeroeightsix/kami/gui/hudgui/LabelHud.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/BaritoneProcess.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/ModuleList.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/Username.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/WaterMark.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/Armor.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/CombatItemCount.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/CrystalDamage.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/TextRadar.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/FPS.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/MemoryUsage.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/Ping.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/ServerBrand.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/TPS.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/Time.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/Direction.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/Durability.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/PlayerSpeed.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/Rotation.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/TimerSpeed.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/world/Biome.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/world/Coordinate.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/world/EntityList.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/world/TextRadar.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/world/WorldTime.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CombatSetting.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Tracers.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
Labels: -gui, enhancement

#1809 [enhancement] Added PacketExplode and PredictExplode to CrystalAura
  src/main/java/me/zeroeightsix/kami/mixin/client/accessor/network/AccessorCPacketUseEntity.java
  src/main/java/me/zeroeightsix/kami/mixin/extension/Network.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt
  src/main/java/me/zeroeightsix/kami/util/combat/CombatUtils.kt
  src/main/resources/mixins.kami.json
Labels: --review-pending, -module, enhancement

#1804 [refactor] Fix issues with and improve AutoObsidian
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoObsidian.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTool.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/PacketLogger.kt
  src/main/java/me/zeroeightsix/kami/process/AutoObsidianProcess.kt
  src/main/java/me/zeroeightsix/kami/process/TemporaryPauseProcess.kt
  src/main/java/me/zeroeightsix/kami/util/BlockUtils.kt
  src/main/java/me/zeroeightsix/kami/util/WorldUtils.kt
  src/main/java/me/zeroeightsix/kami/util/math/BoundingBoxUtils.kt
  src/main/java/me/zeroeightsix/kami/util/math/Direction.kt
  src/main/java/me/zeroeightsix/kami/util/math/VectorUtils.kt
  src/main/java/me/zeroeightsix/kami/util/threads/ThreadSafety.kt
Labels: --changes-requested, -module, bug, enhancement

#1811 [fix] Fast move shulkers in AutoObsidian
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoObsidian.kt
  src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt
Labels: --review-pending, --testing-pending, -module, bug

#1816 [enhancement] Threaded HoleESP, VoidESP, StorageESP, StashLogger, Search
  src/main/java/me/zeroeightsix/kami/command/commands/SearchCommand.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/ModuleList.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/StashLogger.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Search.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/StorageESP.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/VoidESP.kt
  src/main/java/me/zeroeightsix/kami/util/combat/SurroundUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/ESPRenderer.kt
Labels: --review-pending, -module, enhancement

#1817 [enhancement] Hud element scaling
  src/main/java/me/zeroeightsix/kami/gui/hudgui/HudElement.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/KamiHudGui.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/LabelHud.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/BaritoneProcess.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/ModuleList.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/client/WaterMark.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/Armor.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/CombatItemCount.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/misc/Time.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/InventoryViewer.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/player/PlayerModel.kt
Labels: --review-pending, -module, enhancement

#1824 [cleanup] Mixins package
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinMinecraft.java
  src/main/java/me/zeroeightsix/kami/mixin/client/gui/MixinGuiContainer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/gui/MixinGuiIngameForge.java
  src/main/java/me/zeroeightsix/kami/mixin/client/gui/MixinGuiNewChat.java
  src/main/java/me/zeroeightsix/kami/mixin/client/gui/MixinGuiPlayerTabOverlay.java
  src/main/java/me/zeroeightsix/kami/mixin/client/gui/MixinGuiScreen.java
  src/main/java/me/zeroeightsix/kami/mixin/client/player/MixinEntityPlayerSP.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinEntityRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinFontRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinItemRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinLayerArmorBase.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinMapItemRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinRender.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinRenderGlobal.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinTileEntitySignRenderer.java
  src/main/java/me/zeroeightsix/kami/module/modules/chat/ExtraChatHistory.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/KamiMoji.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/ChestStealer.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Freecam.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/AntiFog.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ArmorHide.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ExtraTab.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ItemModel.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/MapPreview.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/NoRender.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ShulkerPreview.kt
  src/main/java/me/zeroeightsix/kami/util/Wrapper.kt
  src/main/java/me/zeroeightsix/kami/util/math/Vec3f.kt
Labels: --review-pending, -other, enhancement

#1837 [refactor] Rewrote InventoryUtils
  src/main/java/me/zeroeightsix/kami/command/commands/DiscordNotifsCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/DupeBookCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/SetBuildingBlockCommand.kt
  src/main/java/me/zeroeightsix/kami/command/commands/SignBookCommand.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/Armor.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/combat/CombatItemCount.kt
  src/main/java/me/zeroeightsix/kami/gui/hudgui/elements/world/EntityList.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/FriendManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/MessageManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/PlayerInventoryManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/PlayerPacketManager.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/WaypointManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/RemoteCommand.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AimBot.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AntiChainPop.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoArmor.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoLog.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoOffhand.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoTrap.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/BedAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CombatSetting.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalBasePlace.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/HoleMiner.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/KillAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/MidClickPearl.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoObsidian.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoSpawner.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTool.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoEat.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/ChestStealer.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/HungerOverlay.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/Nametags.kt
  src/main/java/me/zeroeightsix/kami/setting/config/AbstractConfig.kt
  src/main/java/me/zeroeightsix/kami/setting/config/AbstractMultiConfig.kt
  src/main/java/me/zeroeightsix/kami/setting/groups/SettingGroup.kt
  src/main/java/me/zeroeightsix/kami/setting/groups/SettingMultiGroup.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/DoubleSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/FloatSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/IntegerSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/other/BindSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/other/ColorSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/primitive/BooleanSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/primitive/EnumSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/primitive/StringSetting.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
  src/main/java/me/zeroeightsix/kami/util/InventoryUtils.kt
  src/main/java/me/zeroeightsix/kami/util/combat/CombatUtils.kt
  src/main/java/me/zeroeightsix/kami/util/combat/CrystalUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/TextureUtils.kt
  src/main/java/me/zeroeightsix/kami/util/items/Block.kt
  src/main/java/me/zeroeightsix/kami/util/items/Item.kt
  src/main/java/me/zeroeightsix/kami/util/items/Operation.kt
  src/main/java/me/zeroeightsix/kami/util/items/Slot.kt
Labels: -module, enhancement

#1857 [enhancement] Add custom message to visual range.
  src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt
Labels: -module, enhancement

#1856 [feature] Nearby player check for AutoMend
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoMend.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.kt
  src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt
Labels: --changes-requested, -module, enhancement

#1866 [enhancement] add allowBreak setting to antiAFK.
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
Labels: --changes-requested, -module, enhancement

#1867 [fix] Returning to wrong screen after AntiDisconnect
  src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt
Labels: --info-requested, -module, enhancement

#1874 [cleanup] Cleaned up bunch of stuff for better performance
  src/main/java/me/zeroeightsix/kami/event/ForgeEventProcessor.kt
  src/main/java/me/zeroeightsix/kami/event/events/RenderShaderEvent.kt
  src/main/java/me/zeroeightsix/kami/gui/rgui/windows/ColorPicker.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/PlayerInventoryManager.kt
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinEntityRenderer.java
  src/main/java/me/zeroeightsix/kami/mixin/client/render/MixinRenderManager.java
  src/main/java/me/zeroeightsix/kami/module/modules/client/CommandConfig.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoOffhand.kt
  src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoTool.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/InventoryManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.kt
  src/main/java/me/zeroeightsix/kami/module/modules/render/ESP.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/TextComponent.kt
Labels: --review-pending, -module, enhancement

#1875 [refactor] Use csv format for PacketLogger
  src/main/java/me/zeroeightsix/kami/module/modules/player/PacketLogger.kt
Labels: --changes-requested, -module, enhancement

#1882 [enhancement] Add an OnlyShulkers option to ChestStealer
  src/main/java/me/zeroeightsix/kami/module/modules/player/ChestStealer.kt
Labels: -module, enhancement

#1880 [enhancement] Font Rendering Optimization
  src/main/java/me/zeroeightsix/kami/gui/hudgui/LabelHud.kt
  src/main/java/me/zeroeightsix/kami/gui/rgui/component/Slider.kt
  src/main/java/me/zeroeightsix/kami/manager/managers/KamiMojiManager.kt
  src/main/java/me/zeroeightsix/kami/module/modules/chat/KamiMoji.kt
  src/main/java/me/zeroeightsix/kami/module/modules/client/CustomFont.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/GlStateUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/TextureUtils.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/CharInfo.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/FontGlyphs.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/GlyphChunk.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/KamiFontRenderer.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/Style.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/font/TextComponent.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/texture/AbstractTexture.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/texture/MipmapTexture.kt
  src/main/java/me/zeroeightsix/kami/util/graphics/texture/TextureUtils.kt
  src/main/resources/LICENSE-Slick2D TrueTypeFont.txt
  src/main/resources/assets/kamiblue/fonts/Lato/Lato-Bold.ttf
  src/main/resources/assets/kamiblue/fonts/Lato/Lato-Italic.ttf
  src/main/resources/assets/kamiblue/fonts/Lato/Lato-Regular.ttf
  src/main/resources/assets/kamiblue/fonts/Lato/OFL.txt
  src/main/resources/assets/kamiblue/fonts/Source_Sans_Pro/SourceSansPro-Black.ttf
  src/main/resources/assets/kamiblue/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
  src/main/resources/assets/kamiblue/fonts/Source_Sans_Pro/SourceSansPro-SemiBoldItalic.ttf
Labels: --review-pending, -other, enhancement

#1888 [enhancement] Holding "LMENU" aka Alt can now use a separate step value
  src/main/java/me/zeroeightsix/kami/gui/rgui/component/SettingSlider.kt
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiAFK.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/SettingRegister.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/DoubleSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/FloatSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/IntegerSetting.kt
  src/main/java/me/zeroeightsix/kami/setting/settings/impl/number/NumberSetting.kt
Labels: --review-pending, -gui, enhancement

#1891 [fix] Disable enableInHole by default in surround
  src/main/java/me/zeroeightsix/kami/module/modules/combat/Surround.kt
Labels: -module, enhancement

#1895 [fix] Update SpongePowered Maven URL
  build.gradle
Labels: -dependencies
