Repository kami-blue/client, pull requests merged in 2021-03, with the labels that each got.

#1951 [refactor] Merged LiquidInteract, MultiTask, NoEntityTrace into one module
  src/main/java/org/kamiblue/client/mixin/client/MixinMinecraft.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinEntityRenderer.java
  src/main/java/org/kamiblue/client/mixin/client/world/MixinBlockLiquid.java
  src/main/kotlin/org/kamiblue/client/module/modules/player/BlockInteraction.kt
  src/main/kotlin/org/kamiblue/client/module/modules/player/LiquidInteract.kt
  src/main/kotlin/org/kamiblue/client/module/modules/player/MultiTask.kt
  src/main/kotlin/org/kamiblue/client/module/modules/player/NoEntityTrace.kt
Labels: --testing-pending, -module, enhancement

#2089 [enhancement] useIR for Kotlin compiling to use the beta backend.
  build.gradle
Labels: -blocked, -dependencies, enhancement

#2087 [feature] Add Anchor module
  src/main/kotlin/org/kamiblue/client/module/modules/movement/Anchor.kt
  src/main/kotlin/org/kamiblue/client/module/modules/movement/Strafe.kt
  src/main/kotlin/org/kamiblue/client/util/MovementUtils.kt
Labels: -module, new

#1950 [fix] Freecam mixin compatibility
  src/main/java/org/kamiblue/client/mixin/client/render/MixinRenderGlobal.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinRenderPlayer.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinViewFrustum.java
  src/main/resources/mixins.kami.json
Labels: --review-pending, -incompatible

#2098 [cleanup] RenderEntityEvent
  src/main/java/org/kamiblue/client/mixin/client/render/MixinGlStateManager.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinLayerArmorBase.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinLayerHeldItem.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinRender.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinRenderGlobal.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinRenderLivingBase.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinRenderManager.java
  src/main/kotlin/org/kamiblue/client/event/events/RenderEntityEvent.kt
  src/main/kotlin/org/kamiblue/client/manager/managers/PlayerPacketManager.kt
  src/main/kotlin/org/kamiblue/client/module/modules/render/Chams.kt
  src/main/kotlin/org/kamiblue/client/module/modules/render/ESP.kt
  src/main/kotlin/org/kamiblue/client/module/modules/render/NoRender.kt
  src/main/kotlin/org/kamiblue/client/util/graphics/GlStateUtils.kt
  src/main/resources/mixins.kami.json
Labels: -module, bug, enhancement

#2113 [fix] player.serverBrand must not be null
  src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoObsidian.kt
Labels: -module, bug

#2100 [enhancement] Rewrote World Utils
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoTrap.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/BedAura.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalAura.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalBasePlace.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/Surround.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoFish.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoObsidian.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoSpawner.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoTool.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/NoteBot.kt
  src/main/kotlin/org/kamiblue/client/module/modules/movement/ElytraFlight.kt
  src/main/kotlin/org/kamiblue/client/module/modules/player/NoFall.kt
  src/main/kotlin/org/kamiblue/client/module/modules/player/Scaffold.kt
  src/main/kotlin/org/kamiblue/client/util/WorldUtils.kt
  src/main/kotlin/org/kamiblue/client/util/items/Block.kt
  src/main/kotlin/org/kamiblue/client/util/items/Slot.kt
  src/main/kotlin/org/kamiblue/client/util/math/BoundingBoxUtils.kt
  src/main/kotlin/org/kamiblue/client/util/math/VectorUtils.kt
  src/main/kotlin/org/kamiblue/client/util/world/Block.kt
  src/main/kotlin/org/kamiblue/client/util/world/Check.kt
  src/main/kotlin/org/kamiblue/client/util/world/Interact.kt
  src/main/kotlin/org/kamiblue/client/util/world/PlaceInfo.kt
Labels: -module, enhancement

#2103 [enhancement] AutoEat food preference.
  src/main/kotlin/org/kamiblue/client/module/modules/player/AutoEat.kt
Labels: -module, enhancement

#1947 [refactor] Player Packet Manager
  src/main/java/org/kamiblue/client/mixin/client/MixinMinecraft.java
  src/main/java/org/kamiblue/client/mixin/client/player/MixinEntityPlayerSP.java
  src/main/kotlin/org/kamiblue/client/event/events/OnUpdateWalkingPlayerEvent.kt
  src/main/kotlin/org/kamiblue/client/manager/managers/HotbarManager.kt
  src/main/kotlin/org/kamiblue/client/manager/managers/PlayerPacketManager.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoMend.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoTrap.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/BedAura.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalAura.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalBasePlace.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalESP.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/HoleMiner.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/KillAura.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/Surround.kt
  src/main/kotlin/org/kamiblue/client/module/modules/misc/AutoObsidian.kt
  src/main/kotlin/org/kamiblue/client/module/modules/movement/ElytraFlight.kt
  src/main/kotlin/org/kamiblue/client/module/modules/movement/Flight.kt
  src/main/kotlin/org/kamiblue/client/module/modules/player/Scaffold.kt
  src/main/kotlin/org/kamiblue/client/util/TimeoutFlag.kt
  src/main/kotlin/org/kamiblue/client/util/Wrapper.kt
  src/main/kotlin/org/kamiblue/client/util/world/Interact.kt
Labels: --review-pending, -module, enhancement

#1938 [enhancement] Added ability to modify setting order.
  src/main/kotlin/org/kamiblue/client/gui/clickgui/KamiClickGui.kt
  src/main/kotlin/org/kamiblue/client/gui/clickgui/window/ModuleSettingWindow.kt
  src/main/kotlin/org/kamiblue/client/module/AbstractModule.kt
  src/main/kotlin/org/kamiblue/client/module/modules/client/ClickGUI.kt
Labels: --testing-pending, -gui, enhancement

#1924 [feature] Add Radar including NewChunks
  src/main/kotlin/org/kamiblue/client/event/events/RenderRadarEvent.kt
  src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/world/Radar.kt
  src/main/kotlin/org/kamiblue/client/module/modules/render/NewChunks.kt
Labels: --review-pending, -gui, enhancement

#2088 impr: Add "Disable on Complete" and "Take Off" option for Automend
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoArmor.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/AutoMend.kt
Labels: --changes-requested, -module, enhancement

#1942 refactor: Rewrite the installer
  src/main/java/org/kamiblue/client/installer/Installer.java
  src/main/kotlin/org/kamiblue/client/installer/Installer.kt
Labels: --review-pending, -other, enhancement

#2138 fix: set command printing incorrect value
  src/main/kotlin/org/kamiblue/client/command/commands/SetCommand.kt
Labels: -other, bug

#2143 impr: Add MSPT to TPS HUD Element
  src/main/kotlin/org/kamiblue/client/gui/hudgui/elements/misc/TPS.kt
Labels: --changes-requested, -gui, enhancement

#2150 impr: Use left click to edit String settings
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/StringButton.kt
Labels: -gui, enhancement

#2157 enh: add cursor to string settings.
  src/main/kotlin/org/kamiblue/client/gui/rgui/component/StringButton.kt
Labels: --review-pending, -gui, enhancement

#2159 impr: size option for TextComponents
  src/main/kotlin/org/kamiblue/client/util/EntityUtils.kt
  src/main/kotlin/org/kamiblue/client/util/graphics/font/TextComponent.kt
Labels: --testing-pending, -gui, enhancement

#2158 impr: capture timing setting
  src/main/kotlin/org/kamiblue/client/module/modules/player/PacketLogger.kt
Labels: --review-pending, -other, enhancement

#2155 impr: Separate BoatFly from EntitySpeed
  src/main/java/org/kamiblue/client/mixin/client/render/MixinModelBoat.java
  src/main/kotlin/org/kamiblue/client/module/modules/movement/BoatFly.kt
  src/main/kotlin/org/kamiblue/client/module/modules/movement/EntitySpeed.kt
  src/main/kotlin/org/kamiblue/client/util/EntityUtils.kt
Labels: --testing-pending, -module, enhancement

#2161 fix: Use proper color settings for WaypointFinder and EyeFinder
  src/main/kotlin/org/kamiblue/client/module/modules/render/EyeFinder.kt
  src/main/kotlin/org/kamiblue/client/module/modules/render/WaypointRender.kt
Labels: -module, enhancement

#2162 fix: Use proper color settings for Breadcrumbs
  src/main/kotlin/org/kamiblue/client/module/modules/render/Breadcrumbs.kt
Labels: -module, enhancement

#2165 fix: Use proper color settings for HoleESP and CrystalESP
  src/main/kotlin/org/kamiblue/client/module/modules/combat/CrystalESP.kt
  src/main/kotlin/org/kamiblue/client/module/modules/combat/HoleESP.kt
Labels: -module, enhancement

#2163 enh: Preview color value as it's being changed in ColorPicker
  src/main/kotlin/org/kamiblue/client/gui/rgui/windows/ColorPicker.kt
Labels: -gui, -other, enhancement

#2160 impr: Add ability to sync waypoints from Baritone
  src/main/kotlin/org/kamiblue/client/command/commands/WaypointCommand.kt
  src/main/kotlin/org/kamiblue/client/manager/managers/WaypointManager.kt
Labels: -other, enhancement

#2164 enh: Show waypoints on radar
  src/main/kotlin/org/kamiblue/client/module/modules/render/WaypointRender.kt
Labels: -gui, enhancement

#2149 enh: Added ability to have multiple keys for keybinds
  src/main/kotlin/org/kamiblue/client/command/commands/BindCommand.kt
  src/main/kotlin/org/kamiblue/client/command/commands/MacroCommand.kt
  src/main/kotlin/org/kamiblue/client/gui/clickgui/KamiClickGui.kt
  src/main/kotlin/org/kamiblue/client/gui/hudgui/KamiHudGui.kt
  src/main/kotlin/org/kamiblue/client/manager/managers/MacroManager.kt
  src/main/kotlin/org/kamiblue/client/module/modules/client/CommandConfig.kt
  src/main/kotlin/org/kamiblue/client/setting/settings/impl/other/BindSetting.kt
  src/main/kotlin/org/kamiblue/client/util/Bind.kt
  src/main/kotlin/org/kamiblue/client/util/KeyboardUtils.kt
Labels: -other, enhancement

#2168 impr: Custom AntiAFK AutoReply
  src/main/kotlin/org/kamiblue/client/module/modules/misc/AntiAFK.kt
Labels: -module, enhancement

#2170 enh: Option to show Baritone path on Radar
  src/main/kotlin/org/kamiblue/client/module/modules/client/Baritone.kt
Labels: -gui, enhancement
