Repository kami-blue/client, pull requests merged in 2021-04, with the labels that each got.

#2178 enh: Add BlockOnly option to LiquidInteract
  src/main/kotlin/org/kamiblue/client/module/modules/player/BlockInteraction.kt
Labels: -module, enhancement

#2184 fix: GUI scrolling bug
  src/main/kotlin/org/kamiblue/client/gui/AbstractKamiGui.kt
Labels: -gui, bug

#2185 enh: Boatfly scale modifier
  src/main/java/org/kamiblue/client/mixin/client/render/MixinModelBoat.java
  src/main/kotlin/org/kamiblue/client/module/modules/movement/BoatFly.kt
Labels: -module, enhancement

#2193 bug: Fix color picker preview
  src/main/kotlin/org/kamiblue/client/gui/rgui/windows/ColorPicker.kt
Labels: -gui, bug

#2195 impr: Rewrite Shulker preview and add color options
  src/main/java/org/kamiblue/client/mixin/client/gui/MixinGuiScreen.java
  src/main/kotlin/org/kamiblue/client/module/modules/render/ShulkerPreview.kt
  src/main/kotlin/org/kamiblue/client/util/graphics/RenderUtils2D.kt
Labels: -module, enhancement

#2196 enh: Add option to disable all server side light rendering in NoRender
  src/main/java/org/kamiblue/client/mixin/client/world/MixinWorld.java
  src/main/kotlin/org/kamiblue/client/module/modules/render/NoRender.kt
Labels: --changes-requested, -module, enhancement

#2186 new: Add Xray
  src/main/java/org/kamiblue/client/mixin/client/MixinStateImplementation.java
  src/main/java/org/kamiblue/client/mixin/client/entity/MixinEntity.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinTileRendererDispatcher.java
  src/main/java/org/kamiblue/client/mixin/client/render/MixinVisGraph.java
  src/main/java/org/kamiblue/client/mixin/client/world/MixinBlock.java
  src/main/java/org/kamiblue/client/mixin/client/world/MixinBlockFluidRenderer.java
  src/main/java/org/kamiblue/client/mixin/client/world/MixinBlockModelRenderer.java
  src/main/kotlin/org/kamiblue/client/command/commands/XrayCommand.kt
  src/main/kotlin/org/kamiblue/client/module/modules/render/Xray.kt
  src/main/kotlin/org/kamiblue/client/setting/settings/MutableSetting.kt
  src/main/kotlin/org/kamiblue/client/setting/settings/impl/collection/CollectionSetting.kt
  src/main/resources/mixins.kami.json
Labels: --changes-requested, -module, new
